name: NEST extension module build
on: [push, pull_request]

jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        cpp_compiler: ["gcc", "clang"]
        exclude:
          - cpp_compiler: "clang"
            os: ubuntu-latest
          - cpp_compiler: "gcc"
            os: macos-latest
  
    steps:
      # Checkout the repository
      - name: Checkout nest-extension-module code
        uses: actions/checkout@master

      # Install Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Install ubuntu dependencies
      - name: Ubuntu dependencies
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install libltdl-dev libreadline6-dev libncurses5-dev libgsl0-dev python3-all-dev jq pep8 libpcre3 libpcre3-dev python2-dev libboost-all-dev
          sudo apt-get install openmpi-bin libopenmpi-dev libgsl0-dev tcl8.6 tcl8.6-dev tk8.6-dev
          sudo apt-get install libboost-filesystem-dev libboost-regex-dev libboost-wave-dev libboost-python-dev libboost-program-options-dev libboost-test-dev

      # Install mac OS dependencies
      - name: Mac OS dependencies
        if: runner.os == 'macOS'
        run: |
          brew install coreutils gsl open-mpi automake autoconf libtool
      
      # Install python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install cython scipy matplotlib numpy

      # Run the build script
      - name: Build script
        run: |
          chmod +x build.sh
          set -o pipefail
          ./build.sh
